### ISSUE TITLE
tet request

### ISSUE THREAD

**Issue by fh1999** [reyuwei/nr-reg#1]
data/tet/template.obj
data/tet/target.obj
data/tet/template_tet_dict.pkl

could you please add these files so we can run the code.

**Comment by reyuwei** [comment]
Hi! I uploaded an example [here](https://drive.google.com/drive/folders/1Ww6EPH1rQq-MedebBTKY4deXfTRp4c3I?usp=sharing). You can download and have a test.

**Comment by fh1999** [comment]
Thank you for your data, but I got an error when I run reg_tet.py.
In tetlayer.py, There is no definition of this variable **tet_v_init_gd**.
Looking Forward to your reply.

Traceback (most recent call last):
  File "C:/Users/Admin/Desktop/nr-reg-master/reg_tet.py", line 60, in <module>
    mlayer = TetNonRigidNet(template_mesh, target_mesh, template_tet_rest_dict, wts, device, save_tmp=True, save_folder=exp_folder,  args=args)
  File "C:\Users\Admin\Desktop\nr-reg-master\model\tetlayer.py", line 33, in __init__
    self.init_nh_obj()
  File "C:\Users\Admin\Desktop\nr-reg-master\model\tetlayer.py", line 72, in init_nh_obj
    self.tet_v_init_gd[~v_rest_surface_mask, :] = 1e5
AttributeError: 'TetNonRigidNet' object has no attribute 'tet_v_init_gd'

Process finished with exit code 1

**Comment by fh1999** [comment]
Files required by demo reg_embedded.py request~

**Comment by reyuwei** [comment]
> Thank you for your data, but I got an error when I run reg_tet.py. In tetlayer.py, There is no definition of this variable **tet_v_init_gd**. Looking Forward to your reply.
> 
> Traceback (most recent call last): File "C:/Users/Admin/Desktop/nr-reg-master/reg_tet.py", line 60, in mlayer = TetNonRigidNet(template_mesh, target_mesh, template_tet_rest_dict, wts, device, save_tmp=True, save_folder=exp_folder, args=args) File "C:\Users\Admin\Desktop\nr-reg-master\model\tetlayer.py", line 33, in **init** self.init_nh_obj() File "C:\Users\Admin\Desktop\nr-reg-master\model\tetlayer.py", line 72, in init_nh_obj self.tet_v_init_gd[~v_rest_surface_mask, :] = 1e5 AttributeError: 'TetNonRigidNet' object has no attribute 'tet_v_init_gd'
> 
> Process finished with exit code 1

It is probably a typo, I changed tet_v_init_gd to tet_v_rest_gd in the latest commit. Should be fine.

**Comment by reyuwei** [comment]
> 

The data I use for that is from a another ongoing project. Sorry that I cannot share. But is almost the same with tet code. Just use triangle mesh for this and compute the geodesic distance as well.

**Comment by reyuwei** [comment]
> Files required by demo reg_embedded.py request~

The data I use for that code is from another ongoing project, sorry I cannot share it. But it is almost the same, just use a triangle mesh for the template, and compute the geodesic distance as well.
