### ISSUE TITLE
Data in param.yml

### ISSUE THREAD

**Issue by pmkalshetti** [reyuwei/nr-reg#2]
Hi @reyuwei, thank you for releasing this very useful non-rigid registration code base. Is it possible to provide data files that we can use to run `reg_embedded.py`?

Specifically, can you provide some dummy data to use in `config/param.yml` for the following fields
```
template_mesh_path: data\\template.obj
template_mesh_gd: F:\Projects_fromOnedrive\15_DIGITALHEAD\code\nonrigid\head_gd_another.pkl
target_mesh_path: data\\target.obj
```

**Comment by reyuwei** [comment]
As I explained here #1,  the data I use for that code is from another ongoing project, sorry I cannot share it. But it is almost the same, just use a triangle mesh for the template, and compute the geodesic distance as well.

**Comment by pmkalshetti** [comment]
Thank you.
